@startuml
!include oppdater.pu

arkivmeldingOppdatering -- mappeOppdatering
arkivmeldingOppdatering -- registreringOppdatering
arkivmeldingOppdatering -- dokumentbeskrivelseOppdatering

byggidentOppdateringer -- byggidentOppdatering
byggidentOppdateringer -- byggidentSlett
byggidentOppdateringer -- byggident

dokumentbeskrivelseOppdatering -- dokumentstatus
dokumentbeskrivelseOppdatering -- tilknyttetRegistreringSom
dokumentbeskrivelseOppdatering -- partOppdateringer
dokumentbeskrivelseOppdatering -- skjerming
dokumentbeskrivelseOppdatering -- gradering

innstillingOppdatering -- slettEllerOppdater
innstillingOppdatering -- moetesaksBeskrivelse

journalpostOppdatering *- registreringOppdatering
journalpostOppdatering *- journalposttype
journalpostOppdatering *- journalstatus
journalpostOppdatering *- dokumentflyt
journalpostOppdatering *- presedens

klassifikasjonOppdatering -- referanseTilKlassifikasjon

klassifikasjonOppdateringer -- klassifikasjonOppdatering
klassifikasjonOppdateringer -- klassifikasjonSlett
klassifikasjonOppdateringer -- klassifikasjon


korrespondansepartOppdatering -- korrespondanseparttype
korrespondansepartOppdatering -- administrativEnhet
korrespondansepartOppdatering -- saksbehandler

korrespondansepartOppdateringer -- korrespondansepartOppdatering
korrespondansepartOppdateringer -- korrespondansepartSlett
korrespondansepartOppdateringer -- korrespondansepart

kryssreferanseOppdatering -- referanseTilMappe
kryssreferanseOppdatering -- referanseTilRegistrering
kryssreferanseOppdatering -- referanseTilDokumentbeskrivelse

kryssreferanseOppdateringer -- kryssreferanseOppdatering
kryssreferanseOppdateringer -- kryssreferanseSlett
kryssreferanseOppdateringer -- kryssreferanse

mappeOppdatering -- referanseTilMappe
mappeOppdatering -- partOppdatering
mappeOppdatering -- kryssreferanseOppdateringer
mappeOppdatering -- merknadOppdateringer
mappeOppdatering -- skjerming
mappeOppdatering -- gradering
mappeOppdatering -- klassifikasjonOppdateringer
mappeOppdatering -- eksternNoekkel
mappeOppdatering -- noekkelordOppdateringer
mappeOppdatering -- virksomhetsspesifikkeMetadataOppdateringer

matrikkelnummerOppdateringer -- matrikkelnummer
matrikkelnummerOppdateringer -- matrikkelnummerSlett

merknadOppdatering -- merknadstype

merknadOppdateringer -- merknadOppdatering
merknadOppdateringer -- merknadSlett
merknadOppdateringer -- merknad

moetedeltakerOppdatering -- moetedeltakerFunksjon
moetedeltakerOppdatering -- representerer

moetedeltakerOppdateringer -- moetedeltakerOppdatering
moetedeltakerOppdateringer -- moetedeltakerSlett
moetedeltakerOppdateringer -- moetedeltaker

moetemappeOppdatering -- utvalg
moetemappeOppdatering -- moetedeltakerOppdateringer

moetesakOppdatering *- registreringOppdatering
moetesakOppdatering -- moetesakstype
moetesakOppdatering -- administrativEnhet
moetesakOppdatering -- utredningOppdatering
moetesakOppdatering -- innstillingOppdatering
moetesakOppdatering -- vedtakOppdatering

partOppdatering -- partRolle

partOppdateringer -- partOppdatering
partOppdateringer -- partSlett
partOppdateringer -- part

planidentOppdateringer -- planidentOppdatering
planidentOppdateringer -- planidentSlett
planidentOppdateringer -- planident

punktOppdatering -- koordinatsystem

punktOppdateringer -- punktOppdatering
punktOppdateringer -- punktSlett
punktOppdateringer -- punkt


registreringOppdatering -- referanseTilRegistrering
registreringOppdatering -- referanseTilMappe
registreringOppdatering -- partOppdateringer
registreringOppdatering -- skjerming
registreringOppdatering -- merknadOppdateringer
registreringOppdatering -- korrespondansepartOppdateringer
registreringOppdatering -- klassifikasjonOppdateringer
registreringOppdatering -- eksternNoekkel
registreringOppdatering -- beskrivelseOppdateringer
registreringOppdatering -- forfatterOppdateringer
registreringOppdatering -- graderingOppdateringer
registreringOppdatering -- skjermingOppdateringer

graderingOppdateringer -- graderingOppdatering
skjermingOppdateringer -- skjermingOppdatering

saksmappeOppdatering *- mappeOppdatering
saksmappeOppdatering -- administrativEnhet
saksmappeOppdatering -- saksansvarlig
saksmappeOppdatering -- saksstatus
saksmappeOppdatering -- presedens
saksmappeOppdatering -- matrikkelnummerOppdateringer
saksmappeOppdatering -- byggidentOppdateringer
saksmappeOppdatering -- planidentOppdateringer
saksmappeOppdatering -- punktOppdateringer
saksmappeOppdatering -- adresse

utredningOppdatering -- slettEllerOppdater
utredningOppdatering -- moetesaksBeskrivelse
utredningOppdatering -- dokumentbeskrivelse

vedtakOppdatering -- slettEllerOppdater
vedtakOppdatering -- moetesaksBeskrivelse
vedtakOppdatering -- votering
vedtakOppdatering -- behandlingsprotokoll
vedtakOppdatering -- dokumentbeskrivelse

@enduml
