@startuml
!include opprett.pu

arkivmelding .. registrering
arkivmelding .. mappe

arkivnotat .. dokumentflyt

avskrivning .. avskrivningsmaate
avskrivning .. referanseTilJournalpost

dokumentbeskrivelse .. systemID
dokumentbeskrivelse .. dokumenttype
dokumentbeskrivelse .. dokumentstatus
dokumentbeskrivelse .. dokumentmedium
dokumentbeskrivelse .. tilknyttetRegistreringSom
dokumentbeskrivelse .. merknad
dokumentbeskrivelse .. skjerming
dokumentbeskrivelse .. dokumentobjekt

dokumentflyt .. flytStatus

dokumentobjekt .. variantformat
dokumentobjekt .. format

gradering .. grad

journalpost .. journalposttype
journalpost .. journalstatus
journalpost .. dokumentflyt
journalpost .. presedens

kassasjon .. kassasjonsvedtak

korrespondansepart .. korrespondanseparttype
korrespondansepart .. administrativEnhet
korrespondansepart .. saksbehandler
korrespondansepart .. avskrivning

kryssreferanse .. referanseTilMappe
kryssreferanse .. referanseTilRegistrering
kryssreferanse .. referanseTilDokumentbeskrivelse

mappe .. referanseTilMappe
mappe .. dokumentmedium
mappe .. kryssreferanse
mappe .. part
mappe .. merknad
mappe .. skjerming
mappe .. gradering
mappe .. klassifikasjon
mappe .. eksternNoekkel

merknad .. merknadstype

moetedokument .. registrering
moetedokument .. moetedokumenttype

moetemappe .. moetedeltaker

moetesak .. moetesakstype
moetesak .. administrativEnhet
moetesak .. utredning
moetesak .. moetesaksBeskrivelse
moetesak .. vedtak

part .. partRolle
part .. organisasjonsID
part .. personID

presedens .. presedensStatus

punkt .. koordinatsystem

registrering .. referanseTilMappe
registrering .. part
registrering .. skjerming
registrering .. gradering
registrering .. dokumentbeskrivelse
registrering .. dokumentmedium
registrering .. merknad
registrering .. kryssreferanse
registrering .. korrespondansepart
registrering .. klassifikasjon
registrering .. eksternNoekkel

saksmappe .. administrativEnhet
saksmappe .. saksansvarlig
saksmappe .. saksstatus
saksmappe .. presedens
saksmappe .. matrikkelnummer
saksmappe .. byggident
saksmappe .. planident
saksmappe .. punkt
saksmappe .. adresse

skjerming .. tilgangsrestriksjon
skjerming .. skjermingOpphoererAksjon

utredning .. moetesaksBeskrivelse
utredning .. dokumentbeskrivelse

vedtak .. moetesaksBeskrivelse
vedtak .. votering
vedtak .. behandlingsprotokoll
vedtak .. dokumentbeskrivelse

votering .. moetedeltaker
votering .. moeteStemme
votering .. representerer

@enduml
