@startuml

class adresse {
    +adresse : string
    +postnummer : string
    +poststed : string
}
class arkivmelding {
    +system : string
    +regel : string
    +antallFiler : int
    +mappe : mappe
    +registrering : registrering
}
class arkivnotat {
    +dokumentetsDato : date
    +mottattDato : dateTime
    +sendtDato : dateTime
    +forfallsdato : date
    +offentlighetsvurdertDato : date
    +antallVedlegg : int
    +dokumentflyt : dokumentflyt[]
}
arkivnotat *- registrering
class avskrivning {
    +avskrivningsdato : date
    +avskrevetAv : string
    +avskrivningsmaate : avskrivningsmaate
    +referanseAvskrivesAvJournalpost : referanseTilJournalpost
    +referanseAvskriverJournalpost : referanseTilJournalpost
}
class byggident {
    +bygningsnummer : int
    +endringsloepenummer : int
}
class dokumentbeskrivelse {
    +systemID : systemID
    +dokumenttype : dokumenttype
    +dokumentstatus : dokumentstatus
    +tittel : string
    +beskrivelse : string
    +forfatter : string[]
    +opprettetDato : dateTime
    +opprettetAv : string
    +dokumentmedium : dokumentmedium
    +tilknyttetRegistreringSom : tilknyttetRegistreringSom
    +dokumentnummer : int
    +tilknyttetDato : dateTime
    +tilknyttetAv : string
    +part : part[]
    +merknad : merknad[]
    +skjerming : skjerming
    +gradering : gradering
    +dokumentobjekt : dokumentobjekt[]
}
class dokumentflyt {
    +flytTil : string
    +flytFra : string
    +flytMottattDato : dateTime
    +flytSendtDato : dateTime
    +flytStatus : flytStatus
    +flytMerknad : string
}
class dokumentobjekt {
    +systemID : systemID
    +versjonsnummer : int
    +variantformat : variantformat
    +format : format
    +formatDetaljer : string
    +mimeType : string
    +opprettetDato : dateTime
    +opprettetAv : string
    +filnavn : string
    +referanseDokumentfil : string
    +sjekksum : string
    +sjekksumAlgoritme : string
    +filstoerrelse : int
}
class gradering {
    +grad : grad
    +graderingsdato : dateTime
    +gradertAv : string
    +nedgraderingsdato : dateTime
    +nedgradertAv : string
}
class hendelseslogg {
    +referanseArkivenhet : string
    +beskrivelse : string
    +hendelsestype : string
    +hendelsesdato : dateTime
    +utfortAv : string
}
class journalpost {
    +journalaar : int
    +journalsekvensnummer : int
    +journalpostnummer : int
    +journalposttype : journalposttype
    +journalstatus : journalstatus
    +journaldato : date
    +dokumentetsDato : date
    +mottattDato : dateTime
    +sendtDato : dateTime
    +forfallsdato : date
    +offentlighetsvurdertDato : date
    +antallVedlegg : int
    +journalenhet : string
    +dokumentflyt : dokumentflyt[]
    +presedens : presedens[]
    +avskrivningsdato : date
}
journalpost *- registrering
class kassasjon {
    +kassasjonsvedtak : kassasjonsvedtak
    +kassasjonshjemmel : string
    +bevaringstid : int
    +kassasjonsdato : date
}
class klassifikasjon {
    +klassifikasjonssystemID : string
    +klasseID : string
    +tittel : string
    +erSkjermet : boolean
}
class korrespondansepart {
    +korrespondansepartID : string
    +korrespondanseparttype : korrespondanseparttype
    +erBehandlingsansvarlig : boolean
    +korrespondansepartNavn : string
    +organisasjonid : string
    +personid : string
    +postadresse : string[]
    +postnummer : string
    +poststed : string
    +land : string
    +epostadresse : string
    +telefonnummer : string[]
    +kontaktperson : string
    +administrativEnhet : administrativEnhet
    +saksbehandler : saksbehandler
    +erSkjermet : boolean
    +erPersonnavn : string
    +forsendelsesmaate : string
    +deresReferanse : string
    +avskrivning : avskrivning[]
}
class kryssreferanse {
    +kryssreferanseID : string
    +referanseTilMappe : referanseTilMappe
    +referanseTilRegistrering : referanseTilRegistrering
    +referanseTilDokumentbeskrivelse : referanseTilDokumentbeskrivelse
}
class mappe {
    +systemID : systemID
    +mappeID : string
    +referanseForeldermappe : referanseTilMappe
    +tittel : string
    +offentligTittel : string
    +beskrivelse : string
    +noekkelord : string[]
    +dokumentmedium : dokumentmedium
    +opprettetDato : dateTime
    +opprettetAv : string
    +avsluttetDato : dateTime
    +avsluttetAv : string
    +arkivdel : kode
    +virksomhetsspesifikkeMetadata : anyType
    +part : part[]
    +kryssreferanse : kryssreferanse[]
    +merknad : merknad[]
    +skjerming : skjerming
    +gradering : gradering
    +klassifikasjon : klassifikasjon[]
    +referanseEksternNoekkel : eksternNoekkel
    +mappetype : kode
}
class matrikkelnummer {
    +kommunenummer : string
    +gardsnummer : int
    +bruksnummer : int
    +festenummer : int
    +seksjonsnummer : int
}
class merknad {
    +merknadID : string
    +merknadstekst : string
    +merknadstype : merknadstype
    +merknadsdato : dateTime
    +merknadRegistrertAv : string
    +erSkjermet : boolean
}
class moetedokument {
    +moetedokumenttype : moetedokumenttype
}
moetedokument *- registrering
class moetemappe {
    +moetenummer : string
    +utvalg : utvalg
    +moetedato : date
    +moetested : string
    +referanseForrigeMoete : string
    +referanseNesteMoete : string
    +moetedeltaker : moetedeltaker[]
}
moetemappe *- mappe
class moetesak {
    +moetesakstype : moetesakstype
    +moetesaksaar : int
    +moetesakssekvensnummer : int
    +administrativEnhet : administrativEnhet
    +utredning : utredning
    +innstilling : moetesaksBeskrivelse
    +vedtak : vedtak
}
moetesak *- registrering
class organisasjonsID {
    +identifikator : string
    +landkode : string
}
class part {
    +partID : string
    +partNavn : string
    +partRolle : partRolle
    +organisasjonID : organisasjonsID
    +personID : personID
    +postadresse : string[]
    +postnummer : string
    +poststed : string
    +land : string
    +epostadresse : string
    +telefonnummer : string[]
    +kontaktperson : string
    +virksomhetsspesifikkeMetadata : anyType
    +erSkjermet : boolean
    +erPersonnavn : string
}
class personID {
    +landkode : string
    +identifikator : string
}
class planident {
    +planidentifikasjon : string
    +kommunenummer : string
    +fylkesnummer : string
    +landkode : string
}
class presedens {
    +presedensDato : date
    +opprettetDato : dateTime
    +opprettetAv : string
    +tittel : string
    +beskrivelse : string
    +presedensHjemmel : string
    +rettskildefaktor : string
    +presedensGodkjentDato : dateTime
    +presedensGodkjentAv : string
    +avsluttetDato : dateTime
    +avsluttetAv : string
    +presedensStatus : presedensStatus
}
class punkt {
    +koordinatsystem : koordinatsystem
    +x : double
    +y : double
    +z : double
}
class registrering {
    +systemID : systemID
    +opprettetDato : dateTime
    +opprettetAv : string
    +arkivertDato : dateTime
    +arkivertAv : string
    +referanseForelderMappe : referanseTilMappe
    +arkivdel : kode
    +part : part[]
    +skjerming : skjerming
    +gradering : gradering
    +dokumentbeskrivelse : dokumentbeskrivelse[]
    +registreringsID : string
    +tittel : string
    +offentligTittel : string
    +beskrivelse : string
    +noekkelord : string[]
    +forfatter : string[]
    +dokumentmedium : dokumentmedium
    +virksomhetsspesifikkeMetadata : anyType
    +merknad : merknad[]
    +kryssreferanse : kryssreferanse[]
    +korrespondansepart : korrespondansepart[]
    +klassifikasjon : klassifikasjon[]
    +referanseEksternNoekkel : eksternNoekkel
}
class saksmappe {
    +saksaar : int
    +sakssekvensnummer : int
    +saksdato : date
    +administrativEnhet : administrativEnhet
    +saksansvarlig : saksansvarlig
    +journalenhet : string
    +saksstatus : saksstatus
    +presedens : presedens[]
    +matrikkelnummer : matrikkelnummer[]
    +byggident : byggident[]
    +planident : planident
    +punkt : punkt
    +adresse : adresse[]
}
saksmappe *- mappe
class skjerming {
    +tilgangsrestriksjon : tilgangsrestriksjon
    +skjermingshjemmel : string
    +skjermingOpphoererDato : date
    +skjermingOpphoererAksjon : skjermingOpphoererAksjon
}
class utredning {
    +saksbeskrivelse : moetesaksBeskrivelse
    +innstilling : moetesaksBeskrivelse
    +utredningsdokumenter : dokumentbeskrivelse[]
}
class vedtak {
    +vedtakstekst : moetesaksBeskrivelse
    +votering : votering[]
    +behandlingsprotokoll : behandlingsprotokoll
    +vedtaksdokumenter : dokumentbeskrivelse[]
    +dato : dateTime
}
class votering {
    +moetedeltaker : moetedeltaker
    +stemme : moeteStemme
    +representerer : representerer
}

@enduml
