@startjson
{
  "protokollnavn": "no.ks.fiks.arkiv",
  "navn": "tekstformat",
  "versjon": "v2",
  "kodeliste": [
    {
      "kodeverdi" : "tekst",
      "kodebeskrivelse" : "Tekst som tekstformat"
    },
    {
      "kodeverdi" : "markdown",
      "kodebeskrivelse" : "Markdown markup som tekstformat"
    },
    {
      "kodeverdi" : "html",
      "kodebeskrivelse" : "HTML markup som tekstformat"
    }
  ]
}
@endjson