@startuml
left to right direction

actor KlientsystemA as "Klientsystem A"
actor KlientsystemB as "Klientsystem B"

package Arkivsystem as "Felles data i arkivsystem" {
    usecase "Arkiverer" as uc1
    usecase "Henter fra arkiv" as uc2
}

KlientsystemA --> uc1
KlientsystemA <-- uc2
KlientsystemB <-- uc2
KlientsystemB --> uc1

@enduml