@startuml
skinparam sequenceMessageAlign center 

title "Eksempel på dialog mellom søknadssystem og arkivsystem\nFra start til slutt"


participant Søknadssystem as "Søknadssystem"
participant Arkivsystem as "Arkivsystem"

...Søknadssystem oppretter saksmappe for prosjekt...
Søknadssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett (*1)
Søknadssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt
Søknadssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett.kvittering

... Søknadsprosess med søknader som eventuelt endres \n forblir i søknadssystem til prosjektet avsluttes \n f.eks. søknadsfrist har utgått... 

...Søknadssystem oppretter journalpost(er) med endelige søknad(er) ...
Søknadssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett (*2)
Søknadssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt
Søknadssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett.kvittering

...Søknadssystem avslutter prosjekt...
Søknadssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett (*3)
Søknadssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt
Søknadssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett.kvittering

@enduml