@startjson
{
  "protokollnavn": "no.ks.fiks.arkiv",
  "navn": "moeteregistreringstype",
  "versjon": "v1",
  "definisjon": "Navn på type Navn på type møteregistrering",
  "kodeliste": [
    {
      "kodeverdi" : "MI",
      "kodebeskrivelse" : "Møteinnkalling"
    },
    {
      "kodeverdi" : "SF",
      "kodebeskrivelse" : "Saksframlegg"
    },
    {
      "kodeverdi" : "SP",
      "kodebeskrivelse" : "Saksprotokoll"
    },
    {
      "kodeverdi" : "MP",
      "kodebeskrivelse" : "Møteprotokoll"
    },
    {
      "kodeverdi" : "SL",
      "kodebeskrivelse" : "Saksliste"
    },
    {
      "kodeverdi" : "OL",
      "kodebeskrivelse" : "Offentlig saksliste"
    },
    {
      "kodeverdi" : "VL",
      "kodebeskrivelse" : "Vedlegg til møtesak"
    }
  ]
}
@endjson