@startuml
!include minimum.pu

resultatListeMinimum .. resultatMinimum

resultatMinimum .. mappeMinimum
resultatMinimum .. saksmappeMinimum
resultatMinimum .. registreringMinimum
resultatMinimum .. journalpostMinimum
resultatMinimum .. journalpostMedSaksmappeMinimum
resultatMinimum .. dokumentbeskrivelseMinimum

sokeresultatMinimum .. resultatTypeMinimum
sokeresultatMinimum .. resultatListeMinimum

@enduml
