@startuml

class resultatListeNoekler {
    +resultatNoekler : resultatNoekler[]
}
resultatListeNoekler -- resultatNoekler
class resultatNoekler {
    +mappe : mappeNoekler
    +saksmappe : saksmappeNoekler
    +registrering : registreringNoekler
    +journalpost : journalpostNoekler
    +dokumentbeskrivelse : dokumentbeskrivelseNoekler
}
resultatNoekler -- mappeNoekler
resultatNoekler -- saksmappeNoekler
resultatNoekler -- registreringNoekler
resultatNoekler -- journalpostNoekler
resultatNoekler -- dokumentbeskrivelseNoekler

enum resultatTypeNoekler {
    mappe = mappe
    saksmappe = saksmappe
    registrering = registrering
    journalpost = journalpost
    dokumentbeskrivelse = dokumentbeskrivelse
}
class sokeresultatNoekler {
    +system : string
    +take : int
    +skip : int
    +count : int
    +resultattype : resultatTypeNoekler
    +resultatListe : resultatListeNoekler
}

@enduml
