@startuml
!include noekler.pu

sokeresultatNoekler .. resultatListeNoekler
sokeresultatNoekler .. resultatTypeNoekler

resultatListeNoekler .. resultatNoekler 

resultatNoekler .. mappeNoekler
resultatNoekler .. saksmappeNoekler
resultatNoekler .. registreringNoekler
resultatNoekler .. journalpostNoekler
resultatNoekler .. dokumentbeskrivelseNoekler

@enduml
