@startuml
!include utvidet.pu

resultat .. mappe
resultat .. saksmappe
resultat .. registrering
resultat .. journalpost
resultat .. journalpostMedSaksmappe
resultat .. dokumentbeskrivelse

resultatListe .. resultat

sokeresultat .. resultatType
sokeresultat .. resultatListe

@enduml
