@startjson
  {
    "protokollnavn": "no.ks.fiks.arkiv",
    "navn": "dokumentstatus",
    "versjon": "v2",
    "definisjon": "Status til dokumentet",
    "kodeliste": [
      {
        "kodeverdi" : "B",
        "kodebeskrivelse" : "Dokumentet er under redigering"
      },
      {
        "kodeverdi" : "F",
        "kodebeskrivelse" : "Dokumentet er ferdigstilt"
      }
    ]
  }
@endjson