@startjson
{
  "protokollnavn": "no.ks.fiks.arkiv",
  "navn": "kassasjonsvedtak",
  "versjon": "v1",
  "definisjon": "Handling som skal utføres ved bevaringstidens slutt",
  "kodeliste": [
    {
      "kodeverdi" : "B",
      "kodebeskrivelse" : "Bevares"
    },
    {
      "kodeverdi" : "K",
      "kodebeskrivelse" : "Kasseres"
    },
    {
      "kodeverdi" : "G",
      "kodebeskrivelse" : "Vurderes senere"
    }
  ]
}
@endjson