@startuml

class avskrivning {
    +avskrivningsdato : date
    +avskrevetAv : string
    +avskrivningsmaate : avskrivningsmaate
    +referanseAvskrivesAvJournalpost : referanseTilJournalpost
    +referanseAvskriverJournalpost : referanseTilJournalpost
}
avskrivning -- avskrivningsmaate
avskrivning -- referanseTilJournalpost
class nyAvskrivning {
    +avskrivning : avskrivning
    +referanseTilJournalpost : referanseTilJournalpost
    +korrespondansepartID : string
}
nyAvskrivning -- avskrivning
nyAvskrivning -- referanseTilJournalpost

@enduml
