@startuml
left to right direction
!include sok.pu

sok .. sokdefinisjon

bbox .. koordinatsystem
bbox .. bboxKoordinater

dokumentbeskrivelseFritekstSokdefinisjon .. dokumentbeskrivelseInkluder

dokumentbeskrivelseParameter .. dokumentbeskrivelseSokefelt

dokumentbeskrivelseSokdefinisjon .. dokumentbeskrivelseInkluder
dokumentbeskrivelseSokdefinisjon .. dokumentbeskrivelseSortering

dokumentbeskrivelseSortering .. dokumentbeskrivelseSorteringsfelt
dokumentbeskrivelseSortering .. sorteringType

journalpostFritekstSokdefinisjon .. journalpostInkluder

journalpostMedSaksmappeFritekstSokdefinisjon .. journalpostInkluder

journalpostMedSaksmappeSokdefinisjon .. journalpostInkluder
journalpostMedSaksmappeSokdefinisjon .. journalpostParameter
journalpostMedSaksmappeSokdefinisjon .. journalpostSortering

journalpostParameter .. journalpostSokefelt

journalpostSokdefinisjon .. journalpostInkluder
journalpostSokdefinisjon .. journalpostParameter
journalpostSokdefinisjon .. journalpostSortering

journalpostSortering .. journalpostSorteringsfelt
journalpostSortering .. sorteringType

mappeFritekstSokdefinisjon .. mappeInkluder

mappeParameter .. mappeSokefelt

mappeSokdefinisjon .. mappeInkluder
mappeSokdefinisjon .. mappeParameter
mappeSokdefinisjon .. mappeSortering

mappeSortering .. mappeSorteringsfelt
mappeSortering .. sorteringType

parameter .. operatorType
parameter .. sokVerdier

registreringFritekstSokdefinisjon .. registreringInkluder

registreringParameter .. registreringSokefelt

registreringSokdefinisjon .. registreringInkluder
registreringSokdefinisjon .. registreringParameter
registreringSokdefinisjon .. registreringSortering

registreringSortering .. registreringSorteringsfelt
registreringSortering .. sorteringType

saksmappeFritekstSokdefinisjon .. saksmappeInkluder

saksmappeParameter .. saksmappeSokefelt

saksmappeSokdefinisjon .. saksmappeInkluder
saksmappeSokdefinisjon .. saksmappeParameter
saksmappeSokdefinisjon .. saksmappeSortering

saksmappeSortering .. saksmappeSorteringsfelt
saksmappeSortering .. sorteringType

sokVerdier .. stringvalues
sokVerdier .. datevalues
sokVerdier .. intvalues
sokVerdier .. eksternId
sokVerdier .. klassifikasjonvalues
sokVerdier .. bbox

sokdefinisjon .. responstype

@enduml
