@startuml

class bbox {
    +koordinatsystem : string
    +nedreVenstre : bboxKoordinater
    +oevreHoeyre : bboxKoordinater
}
class bboxKoordinater {
    +x : double
    +y : double
}
class datevalues {
    +value : dateTime[]
}
class dokumentbeskrivelseFritekstSokdefinisjon {
    +inkluder : dokumentbeskrivelseInkluder[]
    +soketekst : string
}
dokumentbeskrivelseFritekstSokdefinisjon *- sokdefinisjon
enum dokumentbeskrivelseInkluder {
    dokumentobjekt = dokumentobjekt
}
class dokumentbeskrivelseParameter {
    +felt : dokumentbeskrivelseSokefelt
}
dokumentbeskrivelseParameter *- parameter
class dokumentbeskrivelseSokdefinisjon {
    +inkluder : dokumentbeskrivelseInkluder[]
    +parametere : dokumentbeskrivelseParameter[]
    +sortering : dokumentbeskrivelseSortering[]
}
dokumentbeskrivelseSokdefinisjon *- sokdefinisjon
enum dokumentbeskrivelseSokefelt {
    dokumentbeskrivelseEksternId = dokumentbeskrivelseEksternId
    dokumentbeskrivelseOpprettetDato = dokumentbeskrivelseOpprettetDato
    dokumentbeskrivelseTittel = dokumentbeskrivelseTittel
    dokumentbeskrivelseDokumenttype = dokumentbeskrivelseDokumenttype
    dokumentbeskrivelseDokumentstatus = dokumentbeskrivelseDokumentstatus
    dokumentbeskrivelseSkjermingTilgangsrestriksjon = dokumentbeskrivelseSkjermingTilgangsrestriksjon
    dokumentbeskrivelseSkjermingSkjermingshjemmel = dokumentbeskrivelseSkjermingSkjermingshjemmel
    dokumentbeskrivelseSkjermingSkjermingsvarighet = dokumentbeskrivelseSkjermingSkjermingsvarighet
    dokumentbeskrivelseSkjermingSkjermingOpphoererDato = dokumentbeskrivelseSkjermingSkjermingOpphoererDato
}
class dokumentbeskrivelseSortering {
    +felt : dokumentbeskrivelseSorteringsfelt
    +type : sorteringType
}
enum dokumentbeskrivelseSorteringsfelt {
    opprettetDato = opprettetDato
}
class eksternId {
    +system : string
    +id : string
}
class intvalues {
    +value : int[]
}
class journalpostFritekstSokdefinisjon {
    +inkluder : journalpostInkluder[]
    +soketekst : string
}
journalpostFritekstSokdefinisjon *- sokdefinisjon
enum journalpostInkluder {
    noekkelord = noekkelord
    kryssreferanse = kryssreferanse
    part = part
    merknad = merknad
    dokumentbeskrivelse = dokumentbeskrivelse
    korrespondansepart = korrespondansepart
    avskrivning = avskrivning
    dokumentflyt = dokumentflyt
}
class journalpostMedSaksmappeFritekstSokdefinisjon {
    +inkluder : journalpostInkluder[]
    +soketekst : string
}
journalpostMedSaksmappeFritekstSokdefinisjon *- sokdefinisjon
class journalpostMedSaksmappeSokdefinisjon {
    +inkluder : journalpostInkluder[]
    +parametere : journalpostParameter[]
    +sortering : journalpostSortering[]
}
journalpostMedSaksmappeSokdefinisjon *- sokdefinisjon
class journalpostParameter {
    +felt : journalpostSokefelt
}
journalpostParameter *- parameter
class journalpostSokdefinisjon {
    +inkluder : journalpostInkluder[]
    +parametere : journalpostParameter[]
    +sortering : journalpostSortering[]
}
journalpostSokdefinisjon *- sokdefinisjon
enum journalpostSokefelt {
    registreringEksternId = registreringEksternId
    registreringOpprettetDato = registreringOpprettetDato
    registreringTittel = registreringTittel
    registreringAdministrativenhet = registreringAdministrativenhet
    registreringJournalpostansvarlig = registreringJournalpostansvarlig
    registreringEndretDato = registreringEndretDato
    registreringPartPartNavn = registreringPartPartNavn
    registreringPartPartRolle = registreringPartPartRolle
    registreringPartPostadresse = registreringPartPostadresse
    registreringPartPostnummer = registreringPartPostnummer
    registreringPartPoststed = registreringPartPoststed
    registreringPartEpostadresse = registreringPartEpostadresse
    registreringSkjermingTilgangsrestriksjon = registreringSkjermingTilgangsrestriksjon
    registreringSkjermingSkjermingshjemmel = registreringSkjermingSkjermingshjemmel
    registreringSkjermingSkjermingsvarighet = registreringSkjermingSkjermingsvarighet
    registreringSkjermingSkjermingOpphoererDato = registreringSkjermingSkjermingOpphoererDato
    journalpostJournalaar = journalpostJournalaar
    journalpostJournalsekvensnummer = journalpostJournalsekvensnummer
    journalpostSaksaar = journalpostSaksaar
    journalpostSakssekvensnummer = journalpostSakssekvensnummer
    journalpostJournalpostnummer = journalpostJournalpostnummer
    journalpostJournalposttype = journalpostJournalposttype
    journalpostJournalstatus = journalpostJournalstatus
    journalpostJournaldato = journalpostJournaldato
    journalpostDokumentetsdato = journalpostDokumentetsdato
    journalpostForfallsdato = journalpostForfallsdato
}
class journalpostSortering {
    +felt : journalpostSorteringsfelt
    +type : sorteringType
}
enum journalpostSorteringsfelt {
    registreringOpprettetDato = registreringOpprettetDato
    journalpostJournaldato = journalpostJournaldato
    journalpostJournalaar-journalsekvensnummer = journalpostJournalaar-journalsekvensnummer
    journalpostJournalpostnummer = journalpostJournalpostnummer
}
class klassifikasjonvalues {
    +klassifikasjonssystem : string[]
    +klasse : string[]
}
class mappeFritekstSokdefinisjon {
    +inkluder : mappeInkluder[]
    +soketekst : string
}
mappeFritekstSokdefinisjon *- sokdefinisjon
enum mappeInkluder {
    noekkelord = noekkelord
    kryssreferanse = kryssreferanse
    part = part
    merknad = merknad
}
class mappeParameter {
    +felt : mappeSokefelt
}
mappeParameter *- parameter
class mappeSokdefinisjon {
    +inkluder : mappeInkluder[]
    +parametere : mappeParameter[]
    +sortering : mappeSortering[]
}
mappeSokdefinisjon *- sokdefinisjon
enum mappeSokefelt {
    mappeEksternId = mappeEksternId
    mappeTittel = mappeTittel
    mappeOpprettetDato = mappeOpprettetDato
    mappeBeskrivelse = mappeBeskrivelse
    mappeNoekkelord = mappeNoekkelord
    mappeAvsluttetDato = mappeAvsluttetDato
    mappeArkivdel = mappeArkivdel
    mappeEndretDato = mappeEndretDato
    mappeMappetype = mappeMappetype
    mappeKlasseKlassifikasjonssystem = mappeKlasseKlassifikasjonssystem
    mappeKlasseKlasseID = mappeKlasseKlasseID
    mappeKlasseTittel = mappeKlasseTittel
    mappeKlasseBeskrivelse = mappeKlasseBeskrivelse
    mappePartPartNavn = mappePartPartNavn
    mappePartPartRolle = mappePartPartRolle
    mappePartPostadresse = mappePartPostadresse
    mappePartPostnummer = mappePartPostnummer
    mappePartPoststed = mappePartPoststed
    mappePartEpostadresse = mappePartEpostadresse
    mappeSkjermingTilgangsrestriksjon = mappeSkjermingTilgangsrestriksjon
    mappeSkjermingSkjermingshjemmel = mappeSkjermingSkjermingshjemmel
    mappeSkjermingSkjermingsvarighet = mappeSkjermingSkjermingsvarighet
    mappeSkjermingSkjermingOpphoererDato = mappeSkjermingSkjermingOpphoererDato
}
class mappeSortering {
    +felt : mappeSorteringsfelt
    +type : sorteringType
}
enum mappeSorteringsfelt {
    mappeOpprettetDato = mappeOpprettetDato
}
enum operatorType {
    equal = equal
    notequal = notequal
    between = between
    lessthan = lessthan
    lessequal = lessequal
    greaterthan = greaterthan
    greaterequal = greaterequal
    inlist = inlist
    wildcardquery = wildcardquery
}
class parameter {
    +operator : operatorType
    +sokVerdier : sokVerdier
}
class registreringFritekstSokdefinisjon {
    +inkluder : registreringInkluder[]
    +soketekst : string
}
registreringFritekstSokdefinisjon *- sokdefinisjon
enum registreringInkluder {
    noekkelord = noekkelord
    kryssreferanse = kryssreferanse
    part = part
    merknad = merknad
    dokumentbeskrivelse = dokumentbeskrivelse
    korrespondansepart = korrespondansepart
}
class registreringParameter {
    +felt : registreringSokefelt
}
registreringParameter *- parameter
class registreringSokdefinisjon {
    +inkluder : registreringInkluder[]
    +parametere : registreringParameter[]
    +sortering : registreringSortering[]
}
registreringSokdefinisjon *- sokdefinisjon
enum registreringSokefelt {
    registreringEksternId = registreringEksternId
    registreringOpprettetDato = registreringOpprettetDato
    registreringTittel = registreringTittel
    registreringAdministrativenhet = registreringAdministrativenhet
    registreringJournalpostansvarlig = registreringJournalpostansvarlig
    registreringEndretDato = registreringEndretDato
    registreringPartPartNavn = registreringPartPartNavn
    registreringPartPartRolle = registreringPartPartRolle
    registreringPartPostadresse = registreringPartPostadresse
    registreringPartPostnummer = registreringPartPostnummer
    registreringPartPoststed = registreringPartPoststed
    registreringPartEpostadresse = registreringPartEpostadresse
    registreringSkjermingTilgangsrestriksjon = registreringSkjermingTilgangsrestriksjon
    registreringSkjermingSkjermingshjemmel = registreringSkjermingSkjermingshjemmel
    registreringSkjermingSkjermingsvarighet = registreringSkjermingSkjermingsvarighet
    registreringSkjermingSkjermingOpphoererDato = registreringSkjermingSkjermingOpphoererDato
}
class registreringSortering {
    +felt : registreringSorteringsfelt
    +type : sorteringType
}
enum registreringSorteringsfelt {
    registreringOpprettetDato = registreringOpprettetDato
}
class saksmappeFritekstSokdefinisjon {
    +inkluder : saksmappeInkluder[]
    +soketekst : string
}
saksmappeFritekstSokdefinisjon *- sokdefinisjon
enum saksmappeInkluder {
    noekkelord = noekkelord
    kryssreferanse = kryssreferanse
    part = part
    merknad = merknad
    presedens = presedens
}
class saksmappeParameter {
    +felt : saksmappeSokefelt
}
saksmappeParameter *- parameter
class saksmappeSokdefinisjon {
    +inkluder : saksmappeInkluder[]
    +parametere : saksmappeParameter[]
    +sortering : saksmappeSortering[]
}
saksmappeSokdefinisjon *- sokdefinisjon
enum saksmappeSokefelt {
    mappeEksternId = mappeEksternId
    mappeTittel = mappeTittel
    mappeOpprettetDato = mappeOpprettetDato
    mappeBeskrivelse = mappeBeskrivelse
    mappeNoekkelord = mappeNoekkelord
    mappeAvsluttetDato = mappeAvsluttetDato
    mappeArkivdel = mappeArkivdel
    mappeEndretDato = mappeEndretDato
    mappeMappetype = mappeMappetype
    mappeKlasseKlassifikasjonssystem = mappeKlasseKlassifikasjonssystem
    mappeKlasseKlasseID = mappeKlasseKlasseID
    mappeKlasseTittel = mappeKlasseTittel
    mappeKlasseBeskrivelse = mappeKlasseBeskrivelse
    mappePartPartNavn = mappePartPartNavn
    mappePartPartRolle = mappePartPartRolle
    mappePartPostadresse = mappePartPostadresse
    mappePartPostnummer = mappePartPostnummer
    mappePartPoststed = mappePartPoststed
    mappePartEpostadresse = mappePartEpostadresse
    mappeSkjermingTilgangsrestriksjon = mappeSkjermingTilgangsrestriksjon
    mappeSkjermingSkjermingshjemmel = mappeSkjermingSkjermingshjemmel
    mappeSkjermingSkjermingsvarighet = mappeSkjermingSkjermingsvarighet
    mappeSkjermingSkjermingOpphoererDato = mappeSkjermingSkjermingOpphoererDato
    sakSaksdato = sakSaksdato
    sakSaksaar = sakSaksaar
    sakSaksekvensnummer = sakSaksekvensnummer
    sakSaksstatus = sakSaksstatus
    sakAdministrativenhet = sakAdministrativenhet
    sakSaksansvarlig = sakSaksansvarlig
    sakMatrikkelnummerKommunenummer = sakMatrikkelnummerKommunenummer
    sakMatrikkelnummerGaardsnummer = sakMatrikkelnummerGaardsnummer
    sakMatrikkelnummerBruksnummer = sakMatrikkelnummerBruksnummer
    sakMatrikkelnummerFestenummer = sakMatrikkelnummerFestenummer
    sakMatrikkelnummerSeksjonsnummer = sakMatrikkelnummerSeksjonsnummer
    sakByggidentBygningsnummer = sakByggidentBygningsnummer
    sakByggidentEndringsloepenummer = sakByggidentEndringsloepenummer
    sakPlanidentStatLandkode = sakPlanidentStatLandkode
    sakPlanidentFylkeFylkesnummer = sakPlanidentFylkeFylkesnummer
    sakPlanidentKommuneKommunenummer = sakPlanidentKommuneKommunenummer
    sakPlanidentPlanidentifikasjon = sakPlanidentPlanidentifikasjon
    sakPartOrganisasjonsid = sakPartOrganisasjonsid
    sakPartPersonid = sakPartPersonid
    sakBbox = sakBbox
}
class saksmappeSortering {
    +felt : saksmappeSorteringsfelt
    +type : sorteringType
}
enum saksmappeSorteringsfelt {
    mappeOpprettetDato = mappeOpprettetDato
    sakSaksaar-saksekvensnummer = sakSaksaar-saksekvensnummer
}
class sok {
    +system : string
    +tidspunkt : dateTime
    +take : int
    +skip : int
    +sokdefinisjon : sokdefinisjon
}
class sokVerdier {
    +stringvalues : stringvalues
    +datevalues : datevalues
    +intvalues : intvalues
    +eksternId : eksternId
    +klassifikasjonvalues : klassifikasjonvalues
    +bbox : bbox
}
class sokdefinisjon {
    +responstype : responstype
}
enum sorteringType {
    synkende = synkende
    stigende = stigende
}
class stringvalues {
    +value : string[]
}

@enduml
