@startjson
{
  "protokollnavn": "no.ks.fiks.arkiv",
  "navn": "format",
  "versjon": "v1",
  "definisjon": "Dokumentets format",
  "kodeliste": [
    {
      "kodeverdi" : "RA-TEKST",
      "kodebeskrivelse" : "Ren tekst"
    },
    {
      "kodeverdi" : "RA-TIFF6",
      "kodebeskrivelse" : "TIFF versjon 6"
    },
    {
      "kodeverdi" : "RA-PDF",
      "kodebeskrivelse" : "PDF/A - ISO 19005-1:2005"
    },
    {
      "kodeverdi" : "RA-XML",
      "kodebeskrivelse" : "XML"
    },
    {
      "kodeverdi" : "RA-JPG",
      "kodebeskrivelse" : "JPG"
    },
    {
      "kodeverdi" : "RA-MPEG-2",
      "kodebeskrivelse" : "MPEG-2"
    },
    {
      "kodeverdi" : "RA-MP3",
      "kodebeskrivelse" : "MP3"
    }
  ]
}
@endjson