@startuml

class dokumentobjektOpprett {
    +dokumentbeskrivelseID : systemID
    +dokumentobjekt : dokumentobjekt
}

dokumentobjektOpprett -- dokumentobjekt
dokumentobjektOpprett -- systemID

@enduml
