@startuml
skinparam sequenceMessageAlign center 

title "Eksempel på dialog mellom rekrutteringssystem og arkivsystem\nFra start til slutt"


participant Rekrutteringssystem as "Rekrutteringssystem"
participant Arkivsystem as "Arkivsystem"

...Rekrutteringssystem oppretter saksmappe for rekrutteringsprosjekt...
Rekrutteringssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding (*1)
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.kvittering

...Rekrutteringssystem oppretter journalpost(er) med søknad(er) ...
Rekrutteringssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding (*2)
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.kvittering

...Rekrutteringssystem endrer journalpost(er) for søknad(er) ...
Rekrutteringssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.oppdater (*3)
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt

...Rekrutteringssystem avslutter rekrutteringsprosjekt...
Rekrutteringssystem -> Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding (*4)
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.mottatt
Rekrutteringssystem <- Arkivsystem : no.ks.fiks.arkiv.v1.arkivering.arkivmelding.kvittering

@enduml