@startuml

class registreringHentResultat {
    +registrering : registrering
    +journalpost : journalpost
}
registreringHentResultat -- registrering
registreringHentResultat -- journalpost

@enduml
