@startjson
{
  "protokollnavn": "no.ks.fiks.arkiv",
  "navn": "arkivdelstatus",
  "versjon": "v2",
  "definisjon": "Status til den arkivperioden som arkivdelen omfatter",
  "kodeliste": [
    {
      "kodeverdi" : "A",
      "kodebeskrivelse" : "Aktiv periode"
    },
    {
      "kodeverdi" : "O",
      "kodebeskrivelse" : "Overlappingsperiode"
    },
    {
      "kodeverdi" : "P",
      "kodebeskrivelse" : "Avsluttet periode"
    },
    {
      "kodeverdi" : "U",
      "kodebeskrivelse" : "Uaktuelle mapper"
    }
  ]
}
@endjson