@startjson
{
  "protokollnavn": "no.ks.fiks.arkiv",
  "navn": "tilgangsrestriksjon",
  "versjon": "v1",
  "definisjon": "Angivelse av at dokumentene som tilhører arkivenheten ikke er offentlig tilgjengelig i henhold til offentlighetsloven eller av en annen grunn",
  "kodeliste": [
    {
      "kodeverdi" : "B",
      "kodebeskrivelse" : "Begrenset etter sikkerhetsinstruksen"
    },
    {
      "kodeverdi" : "K",
      "kodebeskrivelse" : "Konfidensielt etter sikkerhetsinstruksen"
    },
    {
      "kodeverdi" : "H",
      "kodebeskrivelse" : "Hemmeling etter sikkerhetsinstruksen"
    },
    {
      "kodeverdi" : "F",
      "kodebeskrivelse" : "Fortrolig etter sikkerhetsinstruksen"
    },
    {
      "kodeverdi" : "SF",
      "kodebeskrivelse" : "Strengt fortrolig etter sikkerhetsinstruksen"
    },
    {
      "kodeverdi" : "5",
      "kodebeskrivelse" : "Unntatt etter offentlighetsloven § 5"
    },
    {
      "kodeverdi" : "5a",
      "kodebeskrivelse" : "Unntatt etter offentlighetsloven § 5a"
    },
    {
      "kodeverdi" : "6",
      "kodebeskrivelse" : "Unntatt etter offentlighetsloven § 6"
    },
    {
      "kodeverdi" : "11",
      "kodebeskrivelse" : "Unntatt etter offentlighetsloven § 11"
    },
    {
      "kodeverdi" : "XX",
      "kodebeskrivelse" : "Midlertidig sperret"
    }
  ]
}
@endjson