@startuml
!include kvittering.pu

arkivmeldingKvittering .. mappeKvittering
arkivmeldingKvittering .. feilmeldingBase
arkivmeldingKvittering .. registreringKvittering

dokumentbeskrivelseKvittering .. dokumentobjektKvittering

dokumentobjektKvittering .. variantformat

journalpostKvittering *- registreringKvittering
journalpostKvittering .. journalposttype
journalpostKvittering .. journalstatus

mappeKvittering .. referanseTilMappe
mappeKvittering .. eksternNoekkel
mappeKvittering .. opprettetEllerEksisterende

registreringKvittering .. dokumentbeskrivelseKvittering
registreringKvittering .. eksternNoekkel
registreringKvittering .. opprettetEllerEksisterende

@enduml
