@startuml
skinparam sequenceMessageAlign center

title "Oppdater arkivmelding - ikkefunnet"

participant Fagsystem [
    = Fagsystem
]
participant Arkivsystem [
    = Arkivsystem
]

Fagsystem -> Arkivsystem : **no.ks.fiks.arkiv.v1.arkivering.arkivmelding.oppdater**
...Arkivsystem melder at melding er mottatt og håndteres...
Arkivsystem -> Fagsystem : **no.ks.fiks.arkiv.v1.arkivering.arkivmelding.oppdater.mottatt**
...Arkivsystem finner ikke objektet det refereres til i hent-melding...
Arkivsystem -> Fagsystem : **no.ks.fiks.arkiv.v1.feilmelding.ikkefunnet**

@enduml